#!/usr/bin/env node
/**
 * devnet-fund.js
 * ──────────────────────────────────────────────
 * Devnet Faucet から 3 アカウントを自動取得し、
 * .env を live submit 可能な状態で生成する。
 *
 * Usage:
 *   node scripts/devnet-fund.js
 *   node scripts/devnet-fund.js --dry  # .env は書かず stdout のみ
 */
import fs from 'node:fs'
import path from 'node:path'
import { randomBytes } from 'node:crypto'

const FAUCET_URL = 'https://faucet.devnet.rippletest.net/accounts'
const WS_URL = 'wss://s.devnet.rippletest.net:51233'
const ROLES = ['vault_owner', 'lender', 'borrower']
const DRY = process.argv.includes('--dry')

async function fundAccount(role, retries = 3) {
  for (let attempt = 1; attempt <= retries; attempt++) {
    try {
      const res = await fetch(FAUCET_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({})
      })
      if (!res.ok) {
        const text = await res.text().catch(() => '')
        throw new Error(`faucet HTTP ${res.status}: ${text.slice(0, 200)}`)
      }
      const data = await res.json()
      const address = data.account?.address ?? data.account?.classicAddress ?? null
      const seed = data.account?.secret ?? data.account?.seed ?? null
      const balance = data.balance ?? data.amount ?? null
      if (!address || !seed) {
        throw new Error(`unexpected faucet response shape: ${JSON.stringify(data).slice(0, 300)}`)
      }
      console.log(`  [${role}] ${address}  balance=${balance ?? 'unknown'}`)
      return { role, address, seed, balance }
    } catch (err) {
      console.warn(`  [${role}] attempt ${attempt}/${retries} failed: ${err.message}`)
      if (attempt === retries) throw err
      await new Promise((r) => setTimeout(r, 2000 * attempt))
    }
  }
}

function buildEnv(accounts) {
  const seedsMap = {}
  for (const a of accounts) seedsMap[a.address] = a.seed
  const seedsJson = JSON.stringify(seedsMap)
  const authSecret = randomBytes(32).toString('hex')
  const adminPass = randomBytes(12).toString('base64url')

  const vaultOwner = accounts.find((a) => a.role === 'vault_owner')
  const lender = accounts.find((a) => a.role === 'lender')
  const borrower = accounts.find((a) => a.role === 'borrower')

  return `# ============================================================
# XRPL Credit Orchestrator — Devnet Live Submit
# Auto-generated by devnet-fund.js at ${new Date().toISOString()}
# ============================================================

# --- infrastructure ---
PORT=3000
NODE_ENV=development
DATABASE_URL=postgres://postgres:postgres@localhost:5432/xco

# --- auth ---
AUTH_TOKEN_SECRET=${authSecret}
DEV_ADMIN_USERNAME=admin
DEV_ADMIN_PASSWORD=${adminPass}

# --- xrpl ---
XRPL_WS_URL=${WS_URL}
XRPL_NETWORK=devnet
XRPL_LENDING_ENABLED=true

# --- ledger worker ---
LEDGER_WORKER_DRY_RUN=false
LEDGER_WORKER_POLL_MS=5000
LEDGER_WORKER_BATCH_SIZE=3

# --- signing (worker config.js reads these) ---
XRPL_SIGNER_PROVIDER=env
XRPL_SEEDS_JSON=${seedsJson}
XRPL_SEED_FILE=
XRPL_KMS_VENDOR=
XRPL_KMS_KEY_ALIAS=
XRPL_HSM_SLOT=
XRPL_HSM_KEY_LABEL=

# --- signing (env-check.js reads these) ---
SIGNER_PROVIDER=env
SEEDS_JSON=${seedsJson}
SIGNER_SEED_FILE=
SIGNER_KMS_VENDOR=
SIGNER_KMS_KEY_ALIAS=
SIGNER_HSM_SLOT=
SIGNER_HSM_KEY_LABEL=

# --- rate limit ---
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX=200

# --- account reference ---
# vault_owner: ${vaultOwner.address}
# lender:      ${lender.address}
# borrower:    ${borrower.address}
`
}

async function main() {
  console.log('Funding 3 Devnet accounts via faucet...')
  const accounts = []
  for (const role of ROLES) {
    const acc = await fundAccount(role)
    accounts.push(acc)
    // Faucet rate limit防止
    if (role !== ROLES[ROLES.length - 1]) {
      await new Promise((r) => setTimeout(r, 1500))
    }
  }

  console.log('\n--- Account Summary ---')
  for (const a of accounts) {
    console.log(`  ${a.role.padEnd(14)} ${a.address}  (seed hidden)`)
  }

  const envContent = buildEnv(accounts)

  if (DRY) {
    console.log('\n--- .env preview (secrets redacted) ---')
    // Never dump full .env with seeds to stdout
    const redacted = envContent.replace(/"s[A-Za-z0-9]{20,}"/g, '"[REDACTED]"')
    console.log(redacted)
    return
  }

  const envPath = path.resolve(process.cwd(), '.env')
  if (fs.existsSync(envPath)) {
    const backup = envPath + `.backup.${Date.now()}`
    fs.copyFileSync(envPath, backup)
    console.log(`\nBacked up existing .env → ${path.basename(backup)}`)
  }
  fs.writeFileSync(envPath, envContent, 'utf8')
  console.log(`\n.env written.`)
  console.log('Next: npm run check:env && npm run smoke:devnet')

  // Seed file for file-based signer (opt-in, not committed)
  const seedFilePath = path.resolve(process.cwd(), '.devnet-seeds.json')
  const seedMap = {}
  for (const a of accounts) seedMap[a.address] = a.seed
  fs.writeFileSync(seedFilePath, JSON.stringify(seedMap, null, 2), 'utf8')
  console.log(`.devnet-seeds.json written (NEVER COMMIT THIS FILE).`)

  // accounts.json with addresses only (no seeds)
  const jsonPath = path.resolve(process.cwd(), '.devnet-accounts.json')
  const safeAccounts = accounts.map(a => ({ role: a.role, address: a.address, balance: a.balance }))
  fs.writeFileSync(jsonPath, JSON.stringify(safeAccounts, null, 2), 'utf8')
  console.log(`.devnet-accounts.json written (addresses only, no seeds).`)
}

main().catch((err) => {
  console.error('FATAL:', err.message)
  process.exitCode = 1
})
